# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "base_rails"
  config.vm.box_url = "https://s3-us-west-2.amazonaws.com/osf-vagrant-boxes/rails.box"

  config.vm.network "forwarded_port", guest: 3000, host: 3000

  config.vm.synced_folder ".", "/vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  #config.vm.provision "shell", path: "provision.sh"

end
